project:
  type: book
  output-dir: docs
  
execute:
  echo: false

book:
  title: "Roster Crunch"
  author: "Adam Feralio"
  date: "4/27/2024"
  chapters:
    - index.qmd
    - 01_storytime.qmd
    - 02_overview_context.qmd
    - 03_woba_grades_graphs.qmd
    - 04_woba_grades_batters.qmd
    - 05_woba_grades_pitchers.qmd
    - 06_career_woba.qmd
    - 07_correlation_regression.qmd
    - 08_dynasty_thoughts.qmd
    - 09_project_process.qmd
    - 10_project_reflections.qmd
  sidebar: 
    logo: pic_RosterCrunch_Logo.png
  
bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 2
  pdf:
    documentclass: scrreprt

editor: source

